### ISSUE TITLE
测速过程中 frame work 指定 onnxruntim 出现了问题

### ISSUE THREAD

**Issue by 652994331** [Tencent/TurboTransformers#60]
您好 在benchmark 测速过程中 frame work 指定 onnxruntim 是 出现如下问题
![image](https://user-images.githubusercontent.com/51428350/82545882-dbe0f780-9b89-11ea-80e2-4a153c7b381c.png)
已检查torch is availabel 此外 torch 和 turbo transformer 两个 framework 均运行正常
请教一下问题 谢谢

**Comment by feifeibear** [comment]
GPU的onnxrt没装对
pip install onnxruntime-gpu

**Comment by 652994331** [comment]
谢谢。会有个这个问题![image](https://user-images.githubusercontent.com/51428350/82547168-dd132400-9b8b-11ea-83c3-887b97bf2649.png)
已检查/opt/miniconda3/lib 下存在 libcublas.so.10

**Comment by feifeibear** [comment]
1. 没设置对LD_LIBRARY_PATH
2. 安装低版本onnxrt pip install onnxruntime-gpu==1.1.0

**Comment by 652994331** [comment]
通过安装 1.10版的解决了问题 谢谢。 另外想问个关于昨天安装这个tensorflow-gpu(tensorflow 2.0) 的问题， 安装过程中出现了 no space left. 查到本镜像根盘10G（较小）。考虑过删除一些东西，也想请问下有没有比较合理的解决方法。

**Comment by feifeibear** [comment]
turbo不需要按tensorflow 2.0
你可以安装tf 2.0转换模型，然后把tf 2.0卸载掉。
